package cmd

const (
	cmdServerUse                = "server"
	cmdRepositoryUse            = "repository"
	cmdScaleOutRepositoryUse    = "sobr"
	cmdWanAcceleratorUse        = "wanaccelerator"
	cmdMalwareDetectionEventUse = "malwaredetectionevent"
	cmdYaraRuleUse              = "yararule"
	cmdGeneralOptionUse         = "generaloption"
	cmdJobUse                   = "job"
	cmdInventoryUse             = "inventory"
	cmdRestorePointUse          = "restorepoint"
	cmdReplicaUse               = "replica"
	cmdManagedServerUse         = "managedserver"
	cmdObjectRepositoryUse      = "objectrepository"
	cmdProxyUse                 = "proxy"

	cmdGetUse      = "get"
	cmdListUse     = "list"
	cmdDescribeUse = "describe"
	cmdRescanUse   = "rescan"
	cmdEnableUse   = "enable"
	cmdDisableUse  = "disable"
	cmdCloneUse    = "clone"
	cmdDeleteUse   = "delete"
	cmdStartUse    = "start"
	cmdStopUse     = "stop"
	cmdRetryUse    = "retry"
	cmdAddUse      = "add"
	cmdEditUse     = "edit"
	cmdTemplateUse = "template"

	cmdInfoUse = "info"
	cmdTimeUse = "time"
)
